export default{
    setLoading:(state,payload)=>{
        state.loading=payload.loading;
    },
    setToken:(state,payload)=>{
        state.token=payload.token;
    },
    setUploadDialogFlag:(state,payload)=>{
        state.uploadDialogFlag=payload.uploadDialogFlag;
    },
    setDeleteDialogFlag:(state,payload)=>{
        state.deleteDialogFlag=payload.deleteDialogFlag;
    },
    setLogoutDialogFlag:(state,payload)=>{
        state.logoutDialogFlag=payload.logoutDialogFlag;
    },
    setDeleteAccountDialogFlag:(state,payload)=>{
        state.deleteAccountDialogFlag=payload.deleteAccountDialogFlag;
    },
}