export default{
    setLoading:(state,payload)=>{
        state.loading=!state.loading;
    },
    setToken:(state,payload)=>{
        state.token=payload.token;
    },
    setUploadDialogFlag:(state)=>{
        state.uploadDialogFlag=!state.uploadDialogFlag;
    },
    setDeleteDialogFlag:(state)=>{
        state.deleteDialogFlag=!state.deleteDialogFlag;
    },
    setLogoutDialogFlag:(state)=>{
        state.logoutDialogFlag=!state.logoutDialogFlag;
    },
    setDeleteAccountDialogFlag:(state)=>{
        state.deleteAccountDialogFlag=!state.deleteAccountDialogFlag;
    },
}